### ISSUE TITLE
[Feat]: Add welcome words for member joining groups

### ISSUE THREAD

**Issue by rong-xiaoli** [BakaBotTeam/YounBot#2]
When a new member joins into a group, the  bot will choose a welcome word randomly from a list.

**Comment by DoumSof99** [comment]
I am in the EU, and I have set up everything for this repo. Unfortunately, when I tried to sign up to the app, I couldn't because I don't have a Chinese number. I also searched for an alternative, but I read that QQ has become stricter regarding non-Chinese users.

**Comment by rong-xiaoli** [comment]
> I am in the EU, and I have set up everything for this repo. Unfortunately, when I tried to sign up to the app, I couldn't because I don't have a Chinese number. I also searched for an alternative, but I read that QQ has become stricter regarding non-Chinese users.

I've done similar researches and unfortunately there seems to be no existing method registering a QQ account for foreigners. And also, this repo is still WIP so it may not be fully functional in for a while.

**Comment by guimc233** [comment]
https://github.com/BakaBotTeam/YounBot/commit/012aae116468fb1645ae3ec2bc7bf5017044464f
